### YamlMime:ManagedReference
items:
- uid: NeuralNetLearning.LayerConfig.HiddenLayer
  commentId: T:NeuralNetLearning.LayerConfig.HiddenLayer
  id: HiddenLayer
  parent: NeuralNetLearning.LayerConfig
  children:
  - NeuralNetLearning.LayerConfig.HiddenLayer.#ctor(System.Int32,NeuralNetLearning.Maths.Activations.Activation)
  - NeuralNetLearning.LayerConfig.HiddenLayer.Activation
  langs:
  - csharp
  - vb
  name: HiddenLayer
  nameWithType: HiddenLayer
  fullName: NeuralNetLearning.LayerConfig.HiddenLayer
  type: Class
  source:
    remote:
      path: NeuralNetLearning/LayerConfig/HiddenLayer.cs
      branch: master
      repo: https://github.com/nikolaimerritt/NeuralNet.git
    id: HiddenLayer
    path: NeuralNetLearning/LayerConfig/HiddenLayer.cs
    startLine: 4
  assemblies:
  - NeuralNet
  namespace: NeuralNetLearning.LayerConfig
  syntax:
    content: 'public class HiddenLayer : NeuralLayerConfig, IEquatable<NeuralLayerConfig>, IEquatable<HiddenLayer>'
    content.vb: >-
      Public Class HiddenLayer
          Inherits NeuralLayerConfig
          Implements IEquatable(Of NeuralLayerConfig), IEquatable(Of HiddenLayer)
  inheritance:
  - System.Object
  - NeuralNetLearning.LayerConfig.NeuralLayerConfig
  implements:
  - System.IEquatable{NeuralNetLearning.LayerConfig.NeuralLayerConfig}
  - System.IEquatable{NeuralNetLearning.LayerConfig.HiddenLayer}
  inheritedMembers:
  - NeuralNetLearning.LayerConfig.NeuralLayerConfig.Size
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: NeuralNetLearning.LayerConfig.HiddenLayer.Activation
  commentId: P:NeuralNetLearning.LayerConfig.HiddenLayer.Activation
  id: Activation
  parent: NeuralNetLearning.LayerConfig.HiddenLayer
  langs:
  - csharp
  - vb
  name: Activation
  nameWithType: HiddenLayer.Activation
  fullName: NeuralNetLearning.LayerConfig.HiddenLayer.Activation
  type: Property
  source:
    remote:
      path: NeuralNetLearning/LayerConfig/HiddenLayer.cs
      branch: master
      repo: https://github.com/nikolaimerritt/NeuralNet.git
    id: Activation
    path: NeuralNetLearning/LayerConfig/HiddenLayer.cs
    startLine: 6
  assemblies:
  - NeuralNet
  namespace: NeuralNetLearning.LayerConfig
  syntax:
    content: public Activation Activation { get; }
    parameters: []
    return:
      type: NeuralNetLearning.Maths.Activations.Activation
    content.vb: Public ReadOnly Property Activation As Activation
  overload: NeuralNetLearning.LayerConfig.HiddenLayer.Activation*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: NeuralNetLearning.LayerConfig.HiddenLayer.#ctor(System.Int32,NeuralNetLearning.Maths.Activations.Activation)
  commentId: M:NeuralNetLearning.LayerConfig.HiddenLayer.#ctor(System.Int32,NeuralNetLearning.Maths.Activations.Activation)
  id: '#ctor(System.Int32,NeuralNetLearning.Maths.Activations.Activation)'
  parent: NeuralNetLearning.LayerConfig.HiddenLayer
  langs:
  - csharp
  - vb
  name: HiddenLayer(Int32, Activation)
  nameWithType: HiddenLayer.HiddenLayer(Int32, Activation)
  fullName: NeuralNetLearning.LayerConfig.HiddenLayer.HiddenLayer(System.Int32, NeuralNetLearning.Maths.Activations.Activation)
  type: Constructor
  source:
    remote:
      path: NeuralNetLearning/LayerConfig/HiddenLayer.cs
      branch: master
      repo: https://github.com/nikolaimerritt/NeuralNet.git
    id: .ctor
    path: NeuralNetLearning/LayerConfig/HiddenLayer.cs
    startLine: 7
  assemblies:
  - NeuralNet
  namespace: NeuralNetLearning.LayerConfig
  syntax:
    content: public HiddenLayer(int size, Activation activation)
    parameters:
    - id: size
      type: System.Int32
    - id: activation
      type: NeuralNetLearning.Maths.Activations.Activation
    content.vb: Public Sub New(size As Integer, activation As Activation)
  overload: NeuralNetLearning.LayerConfig.HiddenLayer.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: NeuralNetLearning.LayerConfig
  commentId: N:NeuralNetLearning.LayerConfig
  name: NeuralNetLearning.LayerConfig
  nameWithType: NeuralNetLearning.LayerConfig
  fullName: NeuralNetLearning.LayerConfig
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: NeuralNetLearning.LayerConfig.NeuralLayerConfig
  commentId: T:NeuralNetLearning.LayerConfig.NeuralLayerConfig
  parent: NeuralNetLearning.LayerConfig
  name: NeuralLayerConfig
  nameWithType: NeuralLayerConfig
  fullName: NeuralNetLearning.LayerConfig.NeuralLayerConfig
- uid: System.IEquatable{NeuralNetLearning.LayerConfig.NeuralLayerConfig}
  commentId: T:System.IEquatable{NeuralNetLearning.LayerConfig.NeuralLayerConfig}
  parent: System
  definition: System.IEquatable`1
  name: IEquatable<NeuralLayerConfig>
  nameWithType: IEquatable<NeuralLayerConfig>
  fullName: System.IEquatable<NeuralNetLearning.LayerConfig.NeuralLayerConfig>
  nameWithType.vb: IEquatable(Of NeuralLayerConfig)
  fullName.vb: System.IEquatable(Of NeuralNetLearning.LayerConfig.NeuralLayerConfig)
  name.vb: IEquatable(Of NeuralLayerConfig)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    nameWithType: IEquatable
    fullName: System.IEquatable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: NeuralNetLearning.LayerConfig.NeuralLayerConfig
    name: NeuralLayerConfig
    nameWithType: NeuralLayerConfig
    fullName: NeuralNetLearning.LayerConfig.NeuralLayerConfig
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    nameWithType: IEquatable
    fullName: System.IEquatable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: NeuralNetLearning.LayerConfig.NeuralLayerConfig
    name: NeuralLayerConfig
    nameWithType: NeuralLayerConfig
    fullName: NeuralNetLearning.LayerConfig.NeuralLayerConfig
  - name: )
    nameWithType: )
    fullName: )
- uid: System.IEquatable{NeuralNetLearning.LayerConfig.HiddenLayer}
  commentId: T:System.IEquatable{NeuralNetLearning.LayerConfig.HiddenLayer}
  parent: System
  definition: System.IEquatable`1
  name: IEquatable<HiddenLayer>
  nameWithType: IEquatable<HiddenLayer>
  fullName: System.IEquatable<NeuralNetLearning.LayerConfig.HiddenLayer>
  nameWithType.vb: IEquatable(Of HiddenLayer)
  fullName.vb: System.IEquatable(Of NeuralNetLearning.LayerConfig.HiddenLayer)
  name.vb: IEquatable(Of HiddenLayer)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    nameWithType: IEquatable
    fullName: System.IEquatable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: NeuralNetLearning.LayerConfig.HiddenLayer
    name: HiddenLayer
    nameWithType: HiddenLayer
    fullName: NeuralNetLearning.LayerConfig.HiddenLayer
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    nameWithType: IEquatable
    fullName: System.IEquatable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: NeuralNetLearning.LayerConfig.HiddenLayer
    name: HiddenLayer
    nameWithType: HiddenLayer
    fullName: NeuralNetLearning.LayerConfig.HiddenLayer
  - name: )
    nameWithType: )
    fullName: )
- uid: NeuralNetLearning.LayerConfig.NeuralLayerConfig.Size
  commentId: P:NeuralNetLearning.LayerConfig.NeuralLayerConfig.Size
  parent: NeuralNetLearning.LayerConfig.NeuralLayerConfig
  name: Size
  nameWithType: NeuralLayerConfig.Size
  fullName: NeuralNetLearning.LayerConfig.NeuralLayerConfig.Size
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.IEquatable`1
  commentId: T:System.IEquatable`1
  isExternal: true
  name: IEquatable<T>
  nameWithType: IEquatable<T>
  fullName: System.IEquatable<T>
  nameWithType.vb: IEquatable(Of T)
  fullName.vb: System.IEquatable(Of T)
  name.vb: IEquatable(Of T)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    nameWithType: IEquatable
    fullName: System.IEquatable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    nameWithType: IEquatable
    fullName: System.IEquatable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: NeuralNetLearning.LayerConfig.HiddenLayer.Activation*
  commentId: Overload:NeuralNetLearning.LayerConfig.HiddenLayer.Activation
  name: Activation
  nameWithType: HiddenLayer.Activation
  fullName: NeuralNetLearning.LayerConfig.HiddenLayer.Activation
- uid: NeuralNetLearning.Maths.Activations.Activation
  commentId: T:NeuralNetLearning.Maths.Activations.Activation
  parent: NeuralNetLearning.Maths.Activations
  name: Activation
  nameWithType: Activation
  fullName: NeuralNetLearning.Maths.Activations.Activation
- uid: NeuralNetLearning.Maths.Activations
  commentId: N:NeuralNetLearning.Maths.Activations
  name: NeuralNetLearning.Maths.Activations
  nameWithType: NeuralNetLearning.Maths.Activations
  fullName: NeuralNetLearning.Maths.Activations
- uid: NeuralNetLearning.LayerConfig.HiddenLayer.#ctor*
  commentId: Overload:NeuralNetLearning.LayerConfig.HiddenLayer.#ctor
  name: HiddenLayer
  nameWithType: HiddenLayer.HiddenLayer
  fullName: NeuralNetLearning.LayerConfig.HiddenLayer.HiddenLayer
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
