### YamlMime:ManagedReference
items:
- uid: NeuralNetLearning.LayerConfig
  commentId: N:NeuralNetLearning.LayerConfig
  id: NeuralNetLearning.LayerConfig
  children:
  - NeuralNetLearning.LayerConfig.HiddenLayer
  - NeuralNetLearning.LayerConfig.InputLayer
  - NeuralNetLearning.LayerConfig.NeuralLayerConfig
  - NeuralNetLearning.LayerConfig.OutputLayer
  langs:
  - csharp
  - vb
  name: NeuralNetLearning.LayerConfig
  nameWithType: NeuralNetLearning.LayerConfig
  fullName: NeuralNetLearning.LayerConfig
  type: Namespace
  assemblies:
  - NeuralNet
references:
- uid: NeuralNetLearning.LayerConfig.HiddenLayer
  commentId: T:NeuralNetLearning.LayerConfig.HiddenLayer
  name: HiddenLayer
  nameWithType: HiddenLayer
  fullName: NeuralNetLearning.LayerConfig.HiddenLayer
- uid: NeuralNetLearning.LayerConfig.InputLayer
  commentId: T:NeuralNetLearning.LayerConfig.InputLayer
  name: InputLayer
  nameWithType: InputLayer
  fullName: NeuralNetLearning.LayerConfig.InputLayer
- uid: NeuralNetLearning.LayerConfig.NeuralLayerConfig
  commentId: T:NeuralNetLearning.LayerConfig.NeuralLayerConfig
  parent: NeuralNetLearning.LayerConfig
  name: NeuralLayerConfig
  nameWithType: NeuralLayerConfig
  fullName: NeuralNetLearning.LayerConfig.NeuralLayerConfig
- uid: NeuralNetLearning.LayerConfig.OutputLayer
  commentId: T:NeuralNetLearning.LayerConfig.OutputLayer
  name: OutputLayer
  nameWithType: OutputLayer
  fullName: NeuralNetLearning.LayerConfig.OutputLayer
- uid: NeuralNetLearning.LayerConfig
  commentId: N:NeuralNetLearning.LayerConfig
  name: NeuralNetLearning.LayerConfig
  nameWithType: NeuralNetLearning.LayerConfig
  fullName: NeuralNetLearning.LayerConfig
